apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-flask-app
  labels:
    app: python-flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-flask-app
  template:
    metadata:
      labels:
        app: python-flask-app
    spec:
      containers:
      - name: python-flask-app
        image: sidharthpai/challenge3-flaskapp
        ports:
        - containerPort: 80
